### ISSUE TITLE
Unknown fuction: operator#user#define

### ISSUE THREAD

**Issue by egwspiti** [baabelfish/nvim-nim#36]
While editing a nim file with vim, the first time I press `ctrl-]`, vim complains:

    Error detected while processing /.../bundle/nvim-nim/autoload/util.vim:
    line 293:
    E117: Unknown function: operator#user#define

This happens only the first time, subsequent uses of `ctrl-]` result in no errors.
Installing [kana/vim-operator-user](https://github.com/kana/vim-operator-user) fixed the error, so maybe `README.md` should be updated to include this prerequisite. I think this also is the issue that leads into travis-ci builds failing.

**Comment by baabelfish** [comment]
Thanks! Sorry it took me so long to see this. Should be fixed now.
